steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=jr-info
      - --key=cloudbuild-env
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'components'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build:ci']
  - name: 'gcr.io/$PROJECT_ID/hugo'
    arge: ['hugo']
    dir: 'hugo'
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'deploy']
