steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=jr-info
      - --key=cloudbuild-env
  - name: 'gcr.io/$PROJECT_ID/james-richards-io'
    args: ['npm', 'install']
  - name: 'gcr.io/$PROJECT_ID/james-richards-io'
    args: ['npm', 'install']
    dir: 'components'
  - name: 'gcr.io/$PROJECT_ID/james-richards-io'
    args: ['npm', 'run', 'build']
  - name: 'gcr.io/$PROJECT_ID/james-richards-io'
    args: ['npm', 'run', 'deploy']
